
        <div class="col-170">
          <ul id="teritary-nav">
            <li>
              <a href="index.jsp">Toolkit Home</a>
            </li>
            <li>
              <a href="#">Payment API</a>
              <ul>
              <li><a href="paymentcharge.jsp">Charge Amount</a></li>
              <li><a href="paymentrefund.jsp">Refund Amount</a></li>
              <li><a href="paymentreserve.jsp">Reserve Initial Amount</a></li>
              <li><a href="paymentreserveadditional.jsp">Reserve Additional Amount</a></li>
              <li><a href="paymentchargereserved.jsp">Charge Against Reservation</a></li>
              <li><a href="paymentreleasereservation.jsp">Release Reservation</a></li>
              </ul>
            </li>
            <li>
              <a href="#">SMS API</a>
              <ul>
              <li><a href="smssend.jsp">Send SMS</a></li>
              <li><a href="smsquerydelivery.jsp">Query SMS Delivery Status</a></li>
              <li><a href="smssubscribedeliveryreceipts.jsp">Subscribe to SMS Delivery Receipts</a></li>
              <li><a href="smsstopsubscriptiondeliveryreceipts.jsp">Cancel Subscription to SMS Delivery Receipts</a></li>
              <li><a href="smsretrieve.jsp">Retrieve SMS</a></li>
              <li><a href="smssubscribemessagereceipts.jsp">Subscribe to SMS Message Receipts</a></li>
              <li><a href="smsstopsubscriptionmessagereceipts.jsp">Cancel Subscription to SMS Message Receipts</a></li>
              </ul>
            </li>
            <li>
              <a href="#">MMS API</a>
              <ul>
              <li><a href="mmssend.jsp">Send MMS</a></li>
              <li><a href="mmsquerydelivery.jsp">Query MMS Delivery Status</a></li>
              <li><a href="mmssubscribedeliveryreceipts.jsp">Subscribe to MMS Delivery Receipts</a></li>
              <li><a href="mmsstopsubscriptiondeliveryreceipts.jsp">Cancel Subscription to MMS Delivery Receipts</a></li>
              <li><a href="mmsretrieve.jsp">Receive MMS Message List</a></li>
              <li><a href="mmsretrievemessage.jsp">Receive Full MMS Message</a></li>
              <li><a href="mmssubscribemessagereceipts.jsp">Subscribe to MMS Message Receipts</a></li>
              <li><a href="mmsstopsubscriptionmessagereceipts.jsp">Cancel Subscription to MMS Message Receipts</a></li>
              </ul>
            </li>
            <li>
              <a href="#">Location API</a>
              <ul>
              <li><a href="locatesingle.jsp">Locate Single Terminal</a></li>
              <li><a href="locatemultiple.jsp">Locate Multiple Terminals</a></li>
              </ul>
            </li>
          </ul>
        </div>
        