<div id="sub-footer">
        <div id="sub-footer-container">
        </div>
      </div>
<div id="footer">
        <ul>
          <li>
            <a href="mailto:oneapi@gsm.org">Contact Us</a>
          </li>
          <li>
            <a target="_blank" href="http://www.gsmworld.com/privacy.htm">Privacy</a>
          </li>
          <li>
            <a target="_blank" href="http://www.gsmworld.com/documents/gsma_compliance_manual.pdf">Compliance</a>
          </li>
          <li>
            <a target="_blank" href="http://www.gsmworld.com/anti_trust_policy.htm">Anti-Trust Policy Statement</a>
          </li>
          <li>
            <a target="_blank" href="http://www.gsmworld.com/disclaimer.htm">Disclaimer</a>
          </li>
          <li>
            <a target="_blank" href="http://www.gsmworld.com/cookie_policy.htm">Cookie Policy</a>
          </li>
          <li>
            <a target="_blank" href="http://subscription.gsmworld.com">Email Preference Centre</a>
          </li>
          <li>
            <a target="_blank" href="http://twitter.com/oneapi">OneAPI Twitter</a>
          </li>
        </ul><!-- <p>Copyright &copy; 2010 GSM Association. GSM and the GSM Logo are registered and owned by the GSM Association.</p>
   -->
        <p>
          Copyright &copy; 2010 GSMA. All rights reserved.
        </p>
      </div>
