
        <div class="col-170">
          <ul id="teritary-nav">
            <li>
              <a href="index.php">Toolkit Home</a>
            </li>
            <li>
              <a href="#">Payment API</a>
              <ul>
              <li><a href="paymentcharge.php">Charge Amount</a></li>
              <li><a href="paymentrefund.php">Refund Amount</a></li>
              <li><a href="paymentreserve.php">Reserve Initial Amount</a></li>
              <li><a href="paymentreserveadditional.php">Reserve Additional Amount</a></li>
              <li><a href="paymentchargereserved.php">Charge Against Reservation</a></li>
              <li><a href="paymentreleasereservation.php">Release Reservation</a></li>
              </ul>
            </li>
            <li>
              <a href="#">SMS API</a>
              <ul>
              <li><a href="smssend.php">Send SMS</a></li>
              <li><a href="smsquerydelivery.php">Query SMS Delivery Status</a></li>
              <li><a href="smssubscribedeliveryreceipts.php">Subscribe to SMS Delivery Receipts</a></li>
              <li><a href="smsstopsubscriptiondeliveryreceipts.php">Cancel Subscription to SMS Delivery Receipts</a></li>
              <li><a href="smsretrieve.php">Retrieve SMS</a></li>
              <li><a href="smssubscribemessagereceipts.php">Subscribe to SMS Message Receipts</a></li>
              <li><a href="smsstopsubscriptionmessagereceipts.php">Cancel Subscription to SMS Message Receipts</a></li>
              </ul>
            </li>
            <li>
              <a href="#">MMS API</a>
              <ul>
              <li><a href="mmssend.php">Send MMS</a></li>
              <li><a href="mmsquerydelivery.php">Query MMS Delivery Status</a></li>
              <li><a href="mmssubscribedeliveryreceipts.php">Subscribe to MMS Delivery Receipts</a></li>
              <li><a href="mmsstopsubscriptiondeliveryreceipts.php">Cancel Subscription to MMS Delivery Receipts</a></li>
              <li><a href="mmsretrieve.php">Receive MMS Message List</a></li>
              <li><a href="mmsretrievemessage.php">Receive Full MMS Message</a></li>
              <li><a href="mmssubscribemessagereceipts.php">Subscribe to MMS Message Receipts</a></li>
              <li><a href="mmsstopsubscriptionmessagereceipts.php">Cancel Subscription to MMS Message Receipts</a></li>
              </ul>
            </li>
            <li>
              <a href="#">Location API</a>
              <ul>
              <li><a href="locatesingle.php">Locate Single Terminal</a></li>
              <li><a href="locatemultiple.php">Locate Multiple Terminals</a></li>
              </ul>
            </li>
          </ul>
        </div>
        